FROM mcr.microsoft.com/dotnet/core/sdk:3.0-alpine AS build
WORKDIR /app

# copy csproj and restore as distinct layers
COPY *.sln .
COPY aspnetapp/*.csproj ./aspnetapp/
RUN dotnet restore

# copy everything else and build app
COPY aspnetapp/. ./aspnetapp/
WORKDIR /app/aspnetapp
RUN dotnet publish -c Release -o out


FROM mcr.microsoft.com/dotnet/core/aspnet:3.0-alpine AS runtime
WORKDIR /app
COPY --from=build /app/aspnetapp/out ./
# Copie des fichiers de sortie
COPY target/out ./
# Copie de la clé pour JWT
COPY target/keys/public_cert.crt keys/public_cert.crt
# Copie du fichier de configuration
COPY target/epsiconfiguration_docker.xml ./epsiconfiguration.xml
# Fixe l'erreur :
# 	System.NotSupportedException: Globalization Invariant Mode is not supported.
#   	at Microsoft.Data.SqlClient.SqlConnection.TryOpen
RUN apk add --no-cache icu-libs
ENV DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=false
ENTRYPOINT ["dotnet", "aspnetapp.dll"]
